namespace GameList
{
    public class GameList
    {
        public static readonly IReadOnlyList<string> All = new[]
        {
            "Action",
            "Adventure",
            "Action-Adventure",
            "Role-Playing Game (RPG)",
            "Action RPG",
            "Shooter",
            "First-Person Shooter (FPS)",
            "Third-Person Shooter",
            "Battle Royale",
            "Platformer",
            "Open-World",
            "Sandbox",
            "Fighting",
            "Racing",
            "Sports",
            "Simulation",
            "Strategy",
            "Real-Time Strategy (RTS)",
            "Turn-Based Strategy",
            "Multiplayer Online Battle Arena (MOBA)",
            "Survival",
            "Horror",
            "Casual",
            "Stealth",
            "Puzzle",
            "Narrative",
            "Story-Driven",
            "Indie",
            "Roguelike",
            "Roguelite",
            "Dungeon Crawler",
            "Hack and Slash",
            "Beat ’em Up",
            "Metroidvania",
            "Tactical RPG",
            "JRPG",
            "Western RPG",
            "Card Game",
            "Deck-Builder",
            "City Builder",
            "Management",
            "Tycoon",
            "Tower Defense",
            "Idle",
            "Incremental",
            "Party Game",
            "Rhythm",
            "Music",
            "Educational",
            "Trivia",
            "Visual Novel",
            "Dating Sim",
            "Life Simulation",
            "Farming Sim",
            "Cooking Sim",
            "Driving Sim",
            "Flight Sim",
            "Soulslike",
            "Extraction Shooter",
            "Looter Shooter",
            "Hero Shooter",
            "Immersive Sim",
            "Survival Horror",
            "Psychological Horror",
            "Co-op",
            "Online Co-op",
            "Couch Co-op",
            "Competitive",
            "PvP",
            "PvE",
            "Asymmetric Multiplayer",
            "MMO",
            "MMORPG",
            "Action MMO",
            "MMO Lite",
            "Auto-Battler",
            "Grand Strategy",
            "4X Strategy",
            "Wargame",
            "Turn-Based Tactics",
            "Real-Time Tactics",
            "God Game",
            "Colony Sim",
            "Factory Builder",
            "Automation",
            "Physics-Based",
            "Procedural",
            "Sandbox Survival",
            "Text-Based",
            "Interactive Fiction",
            "VR",
            "AR",
            "Mobile",
            "Browser",
            "Cross-Platform",
            "Single-Player",
            "Local Multiplayer",

        };
    }
}
